# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'RainNetWork' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'AFNetworking', '~> 3.2.1'
  # Pods for RainNetWork

  target 'RainNetWorkTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RainNetWorkUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
