# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Demo2-SnapKit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
 
 # Pods for Demo2-SnapKit

  target 'Demo2-SnapKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Demo2-SnapKitUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
